apiVersion: skaffold/v4beta1
kind: Config
build:
  artifacts:
  - image: glensabraham/auth
    context: auth
    sync:
      manual:
      - src: '*.js'
        dest: .
    docker:
      dockerfile: Dockerfile
  local:
    push: false
manifests:
  rawYaml:
  - ./infra/k8s/*
deploy:
  kubectl: {}